<template>
  <div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <div class="is-flex">
      <h1>Catalog</h1>
      <a @click="console" class="button is-primary" href="javascript:void(0);">button</a>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur assumenda atque beatae cupiditate deserunt doloremque ea earum error eum explicabo facere fugiat fugit illum ipsam, iure laboriosam minima mollitia nam nesciunt nulla odio omnis pariatur perferendis placeat quidem quo, rem sunt tempora tenetur unde vitae voluptatum. Accusantium amet eveniet excepturi labore molestias omnis praesentium sint totam. Ab accusamus aspernatur consectetur dolor dolorem earum eius ipsa modi molestiae mollitia nisi obcaecati possimus quod recusandae, reprehenderit sequi similique, voluptatibus. Aspernatur, beatae consequatur eaque eum, expedita fuga hic id impedit molestias mollitia nulla obcaecati provident quas quo repudiandae sequi totam! Ab!</p>
  </div>
</template>

<script>
  export default {
    data () {
      return {
      }
    },
    methods: {
      console () {
        console.log(this.$router.options.routes)
      }
    }
  }
</script>

<style lang="scss">
  @import '../scss/variables';

</style>
